---
title: "Bee Pollination"
output: html_document
date: "2022-11-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(igraph)
library(readxl)
library(plotrix)
library(simer)
library(tidyverse)
```

```{r}

set.seed(1000)

randomness_data1 <- data.frame(width = rep(1:4, each = 5),   # data created
                   length = 1:5,
                   tree_num = round(abs(rnorm(20, mean=462.5, sd=159.375)), 0),
                   bees_required = sample(round(sample(c(20,21,22,23,24,25), size = 20, replace = TRUE))))
```

```{r}
beehive1_l <- 3
beehive1_w <- 4

beehive2_l <- 1
beehive2_w <- 1

beehive3_l <- 3
beehive3_w <- 2

beehive4_l <- 5
beehive4_w <- 1

beehive5_l <- 5
beehive5_w <- 3

beehive6_l <- 1
beehive6_w <- 3


bee_population = 40000
```


```{r}
index_freq <- randomness_data1 |>
  mutate(bees_required = bees_required * tree_num) |>
  mutate(euclid_distance_sqr = (length - beehive1_l)^2+(width - beehive1_w)^2) |>
  mutate(dist_index = case_when(euclid_distance_sqr == 0 ~ 1,
                                euclid_distance_sqr == 1 ~ 2,
                                euclid_distance_sqr == 2 ~ 3,
                                euclid_distance_sqr == 4 ~ 4,
                                euclid_distance_sqr == 5 ~ 5,
                                euclid_distance_sqr == 8 ~ 6,
                                euclid_distance_sqr == 9 ~ 7,
                                euclid_distance_sqr == 10 ~ 8,
                                euclid_distance_sqr == 13 ~ 9,
                                euclid_distance_sqr == 16 ~ 10,
                                euclid_distance_sqr == 17 ~ 11,
                                euclid_distance_sqr == 18 ~ 12,
                                euclid_distance_sqr == 20 ~ 13,
                                euclid_distance_sqr == 25 ~ 14)) |>
  group_by(dist_index) |>
  summarise(index_freq_count = n())

index_freq$index_freq_count[2]

index_required <- randomness_data1 |>
  mutate(bees_required = bees_required * tree_num) |>
  mutate(euclid_distance_sqr = (length - beehive1_l)^2+(width - beehive1_w)^2) |>
  mutate(dist_index = case_when(euclid_distance_sqr == 0 ~ 1,
                                euclid_distance_sqr == 1 ~ 2,
                                euclid_distance_sqr == 2 ~ 3,
                                euclid_distance_sqr == 4 ~ 4,
                                euclid_distance_sqr == 5 ~ 5,
                                euclid_distance_sqr == 8 ~ 6,
                                euclid_distance_sqr == 9 ~ 7,
                                euclid_distance_sqr == 10 ~ 8,
                                euclid_distance_sqr == 13 ~ 9,
                                euclid_distance_sqr == 16 ~ 10,
                                euclid_distance_sqr == 17 ~ 11,
                                euclid_distance_sqr == 18 ~ 12,
                                euclid_distance_sqr == 20 ~ 13,
                                euclid_distance_sqr == 25 ~ 14)) |>
  group_by(dist_index) |>
  summarise(index_required_count = sum(bees_required))

index_required$index_required_count[2]

```

```{r}





ggplotdata <- randomness_data1 |>
  mutate(bees_required = bees_required * tree_num) |>
  mutate(euclid_distance = round(sqrt((length - beehive1_l)^2+(width - beehive1_w)^2),3)) |>
   mutate(euclid_distance_sqr = (length - beehive1_l)^2+(width - beehive1_w)^2) |>
  mutate(dist_index = case_when(euclid_distance_sqr == 0 ~ 1,
                                euclid_distance_sqr == 1 ~ 2,
                                euclid_distance_sqr == 2 ~ 3,
                                euclid_distance_sqr == 4 ~ 4,
                                euclid_distance_sqr == 5 ~ 5,
                                euclid_distance_sqr == 8 ~ 6,
                                euclid_distance_sqr == 9 ~ 7,
                                euclid_distance_sqr == 10 ~ 8,
                                euclid_distance_sqr == 13 ~ 9,
                                euclid_distance_sqr == 16 ~ 10,
                                euclid_distance_sqr == 17 ~ 11,
                                euclid_distance_sqr == 18 ~ 12,
                                euclid_distance_sqr == 20 ~ 13,
                                euclid_distance_sqr == 25 ~ 14))

ggp_1 <- ggplot(ggplotdata, aes(width,length)) +    # Heatmap: Apple Trees number
  geom_tile(aes(fill = tree_num))


farm_plot_1 <- ggp_1 +                                         
  geom_text(aes(label = tree_num)) +
  scale_fill_gradient(low = "white", high = "#1b98e0") 



ggp_2 <- ggplot(ggplotdata, aes(width,length)) +    # Heatmap: Bees requirements for trees
  geom_tile(aes(fill = bees_required))


farm_plot_2 <- ggp_2 +
  geom_text(aes(label = bees_required)) +
  scale_fill_gradient(low = "white", high = "#1b98e0")  

ggp_3 <- ggplot(ggplotdata, aes(width,length)) +    # Heatmap: Euclidean Distance
  geom_tile(aes(fill = euclid_distance))


farm_plot_3 <- ggp_3 +
  geom_text(aes(label = euclid_distance)) +
  scale_fill_gradient(low = "white", high = "#1b98e0")  

ggp_4 <- ggplot(ggplotdata, aes(width,length)) +    # Heatmap: Euclidean Distance Index
  geom_tile(aes(fill = dist_index))


farm_plot_4 <- ggp_4 +
  geom_text(aes(label = dist_index)) +
  scale_fill_gradient(low = "white", high = "#1b98e0")  




farm_plot_1

farm_plot_3

farm_plot_4
```



```{r}


test_model1 <- randomness_data1 |>
  mutate(bees_required = bees_required * tree_num) |>
  mutate(euclid_distance_sqr = (length - beehive1_l)^2+(width - beehive1_w)^2) |>
  mutate(dist_index = case_when(euclid_distance_sqr == 0 ~ 1,
                                euclid_distance_sqr == 1 ~ 2,
                                euclid_distance_sqr == 2 ~ 3,
                                euclid_distance_sqr == 4 ~ 4,
                                euclid_distance_sqr == 5 ~ 5,
                                euclid_distance_sqr == 8 ~ 6,
                                euclid_distance_sqr == 9 ~ 7,
                                euclid_distance_sqr == 10 ~ 8,
                                euclid_distance_sqr == 13 ~ 9,
                                euclid_distance_sqr == 16 ~ 10,
                                euclid_distance_sqr == 17 ~ 11,
                                euclid_distance_sqr == 18 ~ 12,
                                euclid_distance_sqr == 20 ~ 13,
                                euclid_distance_sqr == 25 ~ 14)) |>
  mutate(layer1 = case_when(dist_index == 1 & bee_population - bees_required >= 0 ~ bees_required,
                            dist_index == 1 & bee_population - bees_required < 0 ~ bee_population,
                            dist_index != 1 ~ 0)) |>   # How many bees in a location == index numb
  
  mutate(layer2 = case_when(dist_index == 2 & bee_population - sum(layer1) - index_required$index_required_count[2] >= 0 ~ bees_required,
                            dist_index == 2 & bee_population - sum(layer1) - sum(bees_required) < 0 ~ (bee_population - sum(layer1))/sum(bees_required)*bees_required,
         dist_index != 2 ~ 0)) |>
  
  mutate(layer3 = case_when(dist_index == 3 & bee_population - sum(layer1) - sum(layer2)- index_required$index_required_count[3] >= 0 ~ bees_required,
                            dist_index == 3 & bee_population - sum(layer1) - sum(layer2)- sum(bees_required) < 0 ~ (bee_population - sum(layer1)-sum(layer2))/sum(bees_required)*bees_required,
         dist_index != 3 ~ 0)) |>
  mutate(bees_required_final1 = bees_required - (layer1+layer2+layer3))
```




```{r}
ggplotdata1 <- randomness_data1|>
  mutate(bees_required2 = round(test_model1$bees_required_final1,0))


ggp1 <- ggplot(ggplotdata1, aes(width,length)) +    # Heatmap: Bees requirements for trees
  geom_tile(aes(fill = bees_required2))

farm_plot1 <- ggp1 +
  geom_text(aes(label = bees_required2)) +
  scale_fill_gradient(low = "white", high = "#1b98e0")  
  
farm_plot1
```

# 2 Bee Hive

```{r}
randomness_data2 <- randomness_data1|>
  mutate(bees_required2 = round(test_model1$bees_required_final1,0)) |>
  mutate(euclid_distance_sqr = (length - beehive2_l)^2+(width - beehive2_w)^2) |>
  mutate(dist_index = case_when(euclid_distance_sqr == 0 ~ 1,
                                euclid_distance_sqr == 1 ~ 2,
                                euclid_distance_sqr == 2 ~ 3,
                                euclid_distance_sqr == 4 ~ 4,
                                euclid_distance_sqr == 5 ~ 5,
                                euclid_distance_sqr == 8 ~ 6,
                                euclid_distance_sqr == 9 ~ 7,
                                euclid_distance_sqr == 10 ~ 8,
                                euclid_distance_sqr == 13 ~ 9,
                                euclid_distance_sqr == 16 ~ 10,
                                euclid_distance_sqr == 17 ~ 11,
                                euclid_distance_sqr == 18 ~ 12,
                                euclid_distance_sqr == 20 ~ 13,
                                euclid_distance_sqr == 25 ~ 14))
```

```{r}
index_freq2 <- randomness_data2 |>
  group_by(dist_index) |>
  summarise(index_freq_count = n())


index_required2 <- randomness_data2 |>
  group_by(dist_index) |>
  summarise(index_required_count = sum(bees_required2))

```

```{r}


test_model2 <- randomness_data2 |>
  mutate(layer1 = case_when(dist_index == 1 & bee_population - bees_required2 >= 0 ~ bees_required2,
                            dist_index == 1 & bee_population - bees_required2 < 0 ~ bee_population,
                            dist_index != 1 ~ 0)) |>   # How many bees in a location == index numb
  
  mutate(layer2 = case_when(dist_index == 2 & bee_population - sum(layer1) - index_required2$index_required_count[2] >= 0 ~ bees_required2,
                            dist_index == 2 & bee_population - sum(layer1) - sum(bees_required2) < 0 ~ (bee_population - sum(layer1))/sum(bees_required2)*bees_required2,
         dist_index != 2 ~ 0)) |>
  
  mutate(layer3 = case_when(dist_index == 3 & bee_population - sum(layer1) - sum(layer2)- index_required2$index_required_count[3] >= 0 ~ bees_required2,
                            dist_index == 3 & bee_population - sum(layer1) - sum(layer2)- sum(bees_required2) < 0 ~ (bee_population - sum(layer1)-sum(layer2))/sum(bees_required2)*bees_required2,
         dist_index != 3 ~ 0)) |>
  mutate(bees_required_final = bees_required2 - (layer1+layer2+layer3))
```

```{r}
ggplotdata2 <- randomness_data2|>
  mutate(bees_required3 = round(test_model2$bees_required_final,0))


ggp2 <- ggplot(ggplotdata2, aes(width,length)) +    # Heatmap: Bees requirements for trees
  geom_tile(aes(fill = bees_required3))

farm_plot2 <- ggp2 +
  geom_text(aes(label = bees_required3)) +
  scale_fill_gradient(low = "white", high = "#1b98e0")  
  
farm_plot2
```

#3 Beehive

```{r}
randomness_data3 <- randomness_data2|>
  mutate(bees_required3 = round(test_model2$bees_required_final,0)) |>
  mutate(euclid_distance_sqr = (length - beehive3_l)^2+(width - beehive3_w)^2) |>
  mutate(dist_index = case_when(euclid_distance_sqr == 0 ~ 1,
                                euclid_distance_sqr == 1 ~ 2,
                                euclid_distance_sqr == 2 ~ 3,
                                euclid_distance_sqr == 4 ~ 4,
                                euclid_distance_sqr == 5 ~ 5,
                                euclid_distance_sqr == 8 ~ 6,
                                euclid_distance_sqr == 9 ~ 7,
                                euclid_distance_sqr == 10 ~ 8,
                                euclid_distance_sqr == 13 ~ 9,
                                euclid_distance_sqr == 16 ~ 10,
                                euclid_distance_sqr == 17 ~ 11,
                                euclid_distance_sqr == 18 ~ 12,
                                euclid_distance_sqr == 20 ~ 13,
                                euclid_distance_sqr == 25 ~ 14))
```

```{r}
index_freq3 <- randomness_data3 |>
  group_by(dist_index) |>
  summarise(index_freq_count = n())


index_required3 <- randomness_data3 |>
  group_by(dist_index) |>
  summarise(index_required_count = sum(bees_required3))

```

```{r}


test_model3 <- randomness_data3 |>
  mutate(layer1 = case_when(dist_index == 1 & bee_population - bees_required3 >= 0 ~ bees_required3,
                            dist_index == 1 & bee_population - bees_required3 < 0 ~ bee_population,
                            dist_index != 1 ~ 0)) |>   # How many bees in a location == index numb
  
  mutate(layer2 = case_when(dist_index == 2 & bee_population - sum(layer1) - index_required3$index_required_count[2] >= 0 ~ bees_required3,
                            dist_index == 2 & bee_population - sum(layer1) - sum(bees_required3) < 0 ~ (bee_population - sum(layer1))/sum(bees_required3)*bees_required3,
         dist_index != 2 ~ 0)) |>
  
  mutate(layer3 = case_when(dist_index == 3 & bee_population - sum(layer1) - sum(layer2)- index_required3$index_required_count[3] >= 0 ~ bees_required3,
                            dist_index == 3 & bee_population - sum(layer1) - sum(layer2)- sum(bees_required3) < 0 ~ (bee_population - sum(layer1)-sum(layer2))/sum(bees_required3)*bees_required3,
         dist_index != 3 ~ 0)) |>
  mutate(bees_required_final = bees_required3 - (layer1+layer2+layer3))
```

```{r}
ggplotdata3 <- randomness_data3|>
  mutate(bees_required4 = round(test_model3$bees_required_final,0))


ggp3 <- ggplot(ggplotdata3, aes(width,length)) +    # Heatmap: Bees requirements for trees
  geom_tile(aes(fill = bees_required4))

farm_plot3 <- ggp3 +
  geom_text(aes(label = bees_required4)) +
  scale_fill_gradient(low = "white", high = "#1b98e0")  
  
```

#4 Beehive

```{r}
randomness_data4 <- randomness_data3|>
  mutate(bees_required4 = round(test_model3$bees_required_final,0)) |>
  mutate(euclid_distance_sqr = (length - beehive4_l)^2+(width - beehive4_w)^2) |>
  mutate(dist_index = case_when(euclid_distance_sqr == 0 ~ 1,
                                euclid_distance_sqr == 1 ~ 2,
                                euclid_distance_sqr == 2 ~ 3,
                                euclid_distance_sqr == 4 ~ 4,
                                euclid_distance_sqr == 5 ~ 5,
                                euclid_distance_sqr == 8 ~ 6,
                                euclid_distance_sqr == 9 ~ 7,
                                euclid_distance_sqr == 10 ~ 8,
                                euclid_distance_sqr == 13 ~ 9,
                                euclid_distance_sqr == 16 ~ 10,
                                euclid_distance_sqr == 17 ~ 11,
                                euclid_distance_sqr == 18 ~ 12,
                                euclid_distance_sqr == 20 ~ 13,
                                euclid_distance_sqr == 25 ~ 14))
```

```{r}
index_freq4 <- randomness_data4 |>
  group_by(dist_index) |>
  summarise(index_freq_count = n())


index_required4 <- randomness_data4 |>
  group_by(dist_index) |>
  summarise(index_required_count = sum(bees_required4))

```

```{r}


test_model4 <- randomness_data4 |>
  mutate(layer1 = case_when(dist_index == 1 & bee_population - bees_required4 >= 0 ~ bees_required4,
                            dist_index == 1 & bee_population - bees_required4 < 0 ~ bee_population,
                            dist_index != 1 ~ 0)) |>   # How many bees in a location == index numb
  
  mutate(layer2 = case_when(dist_index == 2 & bee_population - sum(layer1) - index_required4$index_required_count[2] >= 0 ~ bees_required4,
                            dist_index == 2 & bee_population - sum(layer1) - sum(bees_required4) < 0 ~ (bee_population - sum(layer1))/sum(bees_required4)*bees_required4,
         dist_index != 2 ~ 0)) |>
  
  mutate(layer3 = case_when(dist_index == 3 & bee_population - sum(layer1) - sum(layer2)- index_required4$index_required_count[3] >= 0 ~ bees_required4,
                            dist_index == 3 & bee_population - sum(layer1) - sum(layer2)- sum(bees_required4) < 0 ~ (bee_population - sum(layer1)-sum(layer2))/sum(bees_required4)*bees_required4,
         dist_index != 3 ~ 0)) |>
  mutate(bees_required_final = bees_required4 - (layer1+layer2+layer3))
```

```{r}
ggplotdata4 <- randomness_data4|>
  mutate(bees_required5 = round(test_model4$bees_required_final,0))


ggp4 <- ggplot(ggplotdata4, aes(width,length)) +    # Heatmap: Bees requirements for trees
  geom_tile(aes(fill = bees_required5))

farm_plot4 <- ggp4 +
  geom_text(aes(label = bees_required5)) +
  scale_fill_gradient(low = "white", high = "#1b98e0")  
  
```



#5 Beehive


```{r}
randomness_data5 <- randomness_data4|>
  mutate(bees_required5 = round(test_model4$bees_required_final,0)) |>
  mutate(euclid_distance_sqr = (length - beehive5_l)^2+(width - beehive5_w)^2) |>
  mutate(dist_index = case_when(euclid_distance_sqr == 0 ~ 1,
                                euclid_distance_sqr == 1 ~ 2,
                                euclid_distance_sqr == 2 ~ 3,
                                euclid_distance_sqr == 4 ~ 4,
                                euclid_distance_sqr == 5 ~ 5,
                                euclid_distance_sqr == 8 ~ 6,
                                euclid_distance_sqr == 9 ~ 7,
                                euclid_distance_sqr == 10 ~ 8,
                                euclid_distance_sqr == 13 ~ 9,
                                euclid_distance_sqr == 16 ~ 10,
                                euclid_distance_sqr == 17 ~ 11,
                                euclid_distance_sqr == 18 ~ 12,
                                euclid_distance_sqr == 20 ~ 13,
                                euclid_distance_sqr == 25 ~ 14))
```

```{r}
index_freq5 <- randomness_data5 |>
  group_by(dist_index) |>
  summarise(index_freq_count = n())


index_required5 <- randomness_data5 |>
  group_by(dist_index) |>
  summarise(index_required_count = sum(bees_required5))

```

```{r}


test_model5 <- randomness_data5 |>
  mutate(layer1 = case_when(dist_index == 1 & bee_population - bees_required5 >= 0 ~ bees_required5,
                            dist_index == 1 & bee_population - bees_required5 < 0 ~ bee_population,
                            dist_index != 1 ~ 0)) |>   # How many bees in a location == index numb
  
  mutate(layer2 = case_when(dist_index == 2 & bee_population - sum(layer1) - index_required5$index_required_count[2] >= 0 ~ bees_required5,
                            dist_index == 2 & bee_population - sum(layer1) - sum(bees_required5) < 0 ~ (bee_population - sum(layer1))/sum(bees_required5)*bees_required5,
         dist_index != 2 ~ 0)) |>
  
  mutate(layer3 = case_when(dist_index == 3 & bee_population - sum(layer1) - sum(layer2)- index_required5$index_required_count[3] >= 0 ~ bees_required5,
                            dist_index == 3 & bee_population - sum(layer1) - sum(layer2)- sum(bees_required5) < 0 ~ (bee_population - sum(layer1)-sum(layer2))/sum(bees_required5)*bees_required5,
         dist_index != 3 ~ 0)) |>
  mutate(bees_required_final = bees_required5 - (layer1+layer2+layer3))
```

```{r}
ggplotdata5 <- randomness_data5|>
  mutate(bees_required6 = round(test_model5$bees_required_final,0))


ggp5 <- ggplot(ggplotdata5, aes(width,length)) +    # Heatmap: Bees requirements for trees
  geom_tile(aes(fill = bees_required6))

farm_plot5 <- ggp5 +
  geom_text(aes(label = bees_required6)) +
  scale_fill_gradient(low = "white", high = "#1b98e0")  
  
```


#6 Beehive


```{r}
randomness_data6 <- randomness_data5|>
  mutate(bees_required6 = round(test_model5$bees_required_final,0)) |>
  mutate(euclid_distance_sqr = (length - beehive6_l)^2+(width - beehive6_w)^2) |>
  mutate(dist_index = case_when(euclid_distance_sqr == 0 ~ 1,
                                euclid_distance_sqr == 1 ~ 2,
                                euclid_distance_sqr == 2 ~ 3,
                                euclid_distance_sqr == 4 ~ 4,
                                euclid_distance_sqr == 5 ~ 5,
                                euclid_distance_sqr == 8 ~ 6,
                                euclid_distance_sqr == 9 ~ 7,
                                euclid_distance_sqr == 10 ~ 8,
                                euclid_distance_sqr == 13 ~ 9,
                                euclid_distance_sqr == 16 ~ 10,
                                euclid_distance_sqr == 17 ~ 11,
                                euclid_distance_sqr == 18 ~ 12,
                                euclid_distance_sqr == 20 ~ 13,
                                euclid_distance_sqr == 25 ~ 14))
```

```{r}
index_freq6 <- randomness_data6 |>
  group_by(dist_index) |>
  summarise(index_freq_count = n())


index_required6 <- randomness_data6 |>
  group_by(dist_index) |>
  summarise(index_required_count = sum(bees_required6))

```

```{r}


test_model6 <- randomness_data6 |>
  mutate(layer1 = case_when(dist_index == 1 & bee_population - bees_required6 >= 0 ~ bees_required6,
                            dist_index == 1 & bee_population - bees_required6 < 0 ~ bee_population,
                            dist_index != 1 ~ 0)) |>   # How many bees in a location == index numb
  
  mutate(layer2 = case_when(dist_index == 2 & bee_population - sum(layer1) - index_required6$index_required_count[2] >= 0 ~ bees_required6,
                            dist_index == 2 & bee_population - sum(layer1) - sum(bees_required6) < 0 ~ (bee_population - sum(layer1))/sum(bees_required6)*bees_required6,
         dist_index != 2 ~ 0)) |>
  
  mutate(layer3 = case_when(dist_index == 3 & bee_population - sum(layer1) - sum(layer2)- index_required6$index_required_count[3] >= 0 ~ bees_required6,
                            dist_index == 3 & bee_population - sum(layer1) - sum(layer2)- sum(bees_required6) < 0 ~ (bee_population - sum(layer1)-sum(layer2))/sum(bees_required6)*bees_required6,
         dist_index != 3 ~ 0)) |>
  mutate(bees_required_final = bees_required6 - (layer1+layer2+layer3))
```

```{r}
ggplotdata6 <- randomness_data6|>
  mutate(bees_required7 = round(test_model6$bees_required_final,0))


ggp6 <- ggplot(ggplotdata6, aes(width,length)) +    # Heatmap: Bees requirements for trees
  geom_tile(aes(fill = bees_required7))

farm_plot6 <- ggp6 +
  geom_text(aes(label = bees_required7)) +
  scale_fill_gradient(low = "white", high = "#FFFFFF")
  
```



```{r}

farm_plot_2

farm_plot1
farm_plot2
farm_plot3
farm_plot4
farm_plot5
farm_plot6
```





